# Problem-1
- Create arrays with all the data types available in numpy
- **NumPy Data Types**
  - integer
  - boolean
  - unsigned integer
  - float
  - complex float
  - timedelta
  - datetime
  - object
  - string
  - unicode string
  - fixed chunk of memory for other type ( void )


In [7]:
import numpy as np

In [8]:
#integer
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
a.dtype

[ 1  2  3  4  5  6  7  8  9 10]


dtype('int32')

In [19]:
#boolean
a = np.array([0,1,2,3,4,5,6,7,8,9,10], dtype='bool_')
print(a)
a.dtype

[False  True  True  True  True  True  True  True  True  True  True]


dtype('bool')

In [21]:
#unsigned integer
a= np.array([64454], dtype='uint16')
print(a)
a.dtype

[64454]


dtype('uint16')

In [23]:
#float
a= np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7])
print(a)
a.dtype

[1.1 2.2 3.3 4.4 5.5 6.6 7.7]


dtype('float64')

In [24]:
#complex float
a = np.array([1+2j, 2+3j, 4+5j, 5+6j])
print(a)
a.dtype

[1.+2.j 2.+3.j 4.+5.j 5.+6.j]


dtype('complex128')

In [26]:
#timedelta
a=np.timedelta64(6, 'D')
print(a)
a.dtype

6 days


dtype('<m8[D]')

In [28]:
#datetime
a=np.array(['2002-11-01', '2000-07-15', '2002-04-14'], dtype='datetime64')
a

array(['2002-11-01', '2000-07-15', '2002-04-14'], dtype='datetime64[D]')

In [29]:
#object
a = np.array([1,3,5,7,8,9,10], dtype='O')
a

array([1, 3, 5, 7, 8, 9, 10], dtype=object)

In [33]:
#string
a = np.array(['Hi', 'everyone',"I'm Bharath"])
print(a)
a.dtype

['Hi' 'everyone' "I'm Bharath"]


dtype('<U11')

In [34]:
#unicode string
a = np.array([u'\u03bcm', u'\u2202r', u'\u2206\u03bb'], dtype='U')
a

array(['μm', '∂r', '∆λ'], dtype='<U2')

In [37]:
#void
x=np.void([])
x

array([], dtype='|V8')